<a href="https://colab.research.google.com/github/MariiaBulavina/GoIT-WEB-Project/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення

In [5]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [9]:
array = np.random.randint(1, 11, (5, 5))
print(array)

[[ 2  1 10  9  8]
 [ 6  3  6  2  7]
 [ 7  4  2  3  8]
 [10  3  5  6  3]
 [ 3  9  1  4  1]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [10]:
array = np.random.rand(4, 4)
print(array)

[[0.70344287 0.85067421 0.2282892  0.47870985]
 [0.43878014 0.29111194 0.29973027 0.23524193]
 [0.52477651 0.52366473 0.87263274 0.58710612]
 [0.66935943 0.1869501  0.87374603 0.17939847]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [44]:
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

print('Array 1:', array1)
print('Array 2:', array2)

addition_result = array1 + array2
print('\nAddition result:', addition_result)

subtraction_result = array1 - array2
print('Subtraction result:', subtraction_result)

multiplication_result = array1 * array2
print('Multiplication result:', multiplication_result)

Array 1: [ 4  7  7 10  8]
Array 2: [6 4 7 8 8]

Addition result: [10 11 14 18 16]
Subtraction result: [-2  3  0  2  0]
Multiplication result: [24 28 49 80 64]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [45]:
vector1 = np.random.randint(1, 100, 7)
vector2 = np.random.randint(1, 100, 7)

print('Vector 1:', vector1)
print('Vector 2:', vector2)

scalar_product = np.dot(vector1, vector2)
print('\nScalar product:', scalar_product)

Vector 1: [42 97 62 23  3 14 49]
Vector 2: [69 70 13 77 41 76 15]

Scalar product: 14187


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [46]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print('Matrix 1:\n', matrix1)
print('\nMatrix 2:\n', matrix2)

result_matrix = np.dot(matrix1, matrix2)
print('\nResult matrix:\n', result_matrix)

Matrix 1:
 [[8 6]
 [2 9]]

Matrix 2:
 [[ 1 10  9]
 [ 9  9  4]]

Result matrix:
 [[ 62 134  96]
 [ 83 101  54]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [47]:
matrix = np.random.randint(1, 11, size=(3, 3))

print('Matrix:\n', matrix)

inverse_matrix = np.linalg.inv(matrix)

print('\nInverse matrix:\n', inverse_matrix)

Matrix:
 [[10 10  4]
 [ 5  4  1]
 [ 3  3  8]]

Inverse matrix:
 [[-4.26470588e-01  1.00000000e+00  8.82352941e-02]
 [ 5.44117647e-01 -1.00000000e+00 -1.47058824e-01]
 [-4.41176471e-02 -6.53072367e-17  1.47058824e-01]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [48]:
matrix = np.random.rand(4, 4)

print('Matrix:\n', matrix)

transposed_matrix = np.transpose(matrix)

print('\nTransposed matrix:\n', transposed_matrix)


Matrix:
 [[0.95684047 0.41273139 0.34869457 0.55379524]
 [0.27366794 0.01853383 0.44793725 0.75244551]
 [0.75003047 0.58236511 0.64211554 0.25387811]
 [0.66055055 0.18558454 0.19754865 0.79993239]]

Transposed matrix:
 [[0.95684047 0.27366794 0.75003047 0.66055055]
 [0.41273139 0.01853383 0.58236511 0.18558454]
 [0.34869457 0.44793725 0.64211554 0.19754865]
 [0.55379524 0.75244551 0.25387811 0.79993239]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [49]:
matrix = np.random.randint(1, 11, size=(3, 4))

print('Matrix:\n', matrix)

vector = np.random.randint(1, 11, size=4)

print('\nVector:\n', vector)

result = np.dot(matrix, vector)

print('\nResult:\n', result)


Matrix:
 [[ 2  3  3  7]
 [10  5  5  5]
 [ 1  6  7  1]]

Vector:
 [ 2  1 10 10]

Result:
 [107 125  88]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [50]:
matrix = np.random.rand(2, 3)

print('Matrix:\n', matrix)

vector = np.random.rand(3)

print('\nVector:\n', vector)

result = np.dot(matrix, vector)

print('\nResult:\n', result)

Matrix:
 [[0.95085465 0.46460101 0.99842966]
 [0.12132719 0.0909396  0.27346719]]

Vector:
 [0.0977364  0.53080791 0.22049718]

Result:
 [0.55969792 0.12042828]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [51]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print('Matrix 1:\n', matrix1)
print('\nMatrix 2:\n', matrix2)

result = matrix1 * matrix2

print('\nResult:\n', result)

Matrix 1:
 [[4 6]
 [7 8]]

Matrix 2:
 [[8 7]
 [5 6]]

Result:
 [[32 42]
 [35 48]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [52]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print('Matrix 1:\n', matrix1)
print('\nMatrix 2:\n', matrix2)

product = np.dot(matrix1, matrix2)

print('\nProduct:\n', product)

Matrix 1:
 [[3 1]
 [6 8]]

Matrix 2:
 [[ 1 10]
 [ 8 10]]

Product:
 [[ 11  40]
 [ 70 140]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [53]:
matrix = np.random.randint(1, 101, size=(5, 5))

print('Matrix:\n', matrix)

sum = np.sum(matrix)

print('\nSum of matrix elements:', sum)


Matrix:
 [[ 65  90  67  10  50]
 [ 62  38  73  63  21]
 [ 14  74  74  25  95]
 [ 27   3   5  14  62]
 [ 75 100  59  99  74]]

Sum of matrix elements: 1339


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [54]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print('Matrix 1:\n', matrix1)
print('\nMatrix 2:\n', matrix2)

result = matrix1 - matrix2

print('\nResult:\n', result)

Matrix 1:
 [[ 1  8 10  6]
 [ 1  6  3  2]
 [ 5  1  6  1]
 [ 4 10 10  5]]

Matrix 2:
 [[ 2  8  4  2]
 [ 4  6  9  6]
 [ 2 10  6  8]
 [ 2  8  6  8]]

Result:
 [[-1  0  6  4]
 [-3  0 -6 -4]
 [ 3 -9  0 -7]
 [ 2  2  4 -3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [55]:
matrix = np.random.rand(3, 3)

print('Matrix:\n', matrix)

sum = np.sum(matrix, axis=1)
column_vectorn = sum.reshape(-1, 1)

print('\nColumn vector:\n', column_vectorn)

Matrix:
 [[0.6357408  0.01071921 0.69880079]
 [0.06073265 0.35673393 0.34791422]
 [0.8705795  0.35272336 0.26991618]]

Column vector:
 [[1.3452608 ]
 [0.7653808 ]
 [1.49321904]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [56]:
matrix = np.random.randint(1, 100, size=(3, 4))

print('Matrix:\n', matrix)

squared_matrix = np.square(matrix)

print('\nSquared matrix:\n', squared_matrix)

Matrix:
 [[ 2 56 65 68]
 [ 8 33 48 71]
 [74 20 91 54]]

Squared matrix:
 [[   4 3136 4225 4624]
 [  64 1089 2304 5041]
 [5476  400 8281 2916]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [57]:
vector = np.random.randint(1, 51, size=4)

print('Vector:\n', vector)

sqrt_vector = np.sqrt(vector)

print('\nVector with square roots:\n', sqrt_vector)

Vector:
 [ 5 47 23 30]

Vector with square roots:
 [2.23606798 6.8556546  4.79583152 5.47722558]
